name: artifact
channels:
  - conda-forge
  - defaults
dependencies:
  - mamba
  - python=3.8
  - pip
  - dvc
  - numpy
  - matplotlib
  - pandas
  - scipy
  - seaborn
  - sympy
  - dask
  - altair
  - tqdm
  - click
  - plotly
  - optuna
  - xlrd
  - scikit-learn
  - statsmodels
  - ipywidgets
  - pip:
    - jupyter-book
    - pyscaffoldext-dsproject
  # for development only (could also be kept in a separate environment file)
  - pyscaffold
  - pycodestyle
  - pydocstyle
  - jupyterlab
  - nodejs
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - sphinx
  - nbdime
  - nbstripout
  - recommonmark
